<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hand">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <!-- prefix: used for joint and link names. Needed to distinguish joints and TFs in case of multiple arm instances. -->
  <xacro:macro name="hand" params="connected_to:='' prefix:=^| rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0 description_pkg:=franka_description">
    <xacro:unless value="${connected_to == ''}">
      <joint name="${prefix}hand_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${prefix}hand"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>
    <xacro:link name="hand">
      <self_collision_geometries>
      <collision>
        <origin xyz="0 0 0.04" rpy="0 ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${0.04+safety_distance}" length="0.1" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 -0.05 0.04" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.05 0.04" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.1" rpy="0 ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${0.02+safety_distance}" length="0.1" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 -0.05 0.1" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.02+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.05 0.1" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.02+safety_distance}"  />
        </geometry>
      </collision>
      </self_collision_geometries>
    </xacro:link>
    <link name="${prefix}leftfinger">
      <visual>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://franka_description/meshes/collision/finger.stl" />
        </geometry>
      </collision>
      <xacro:inertial name="leftfinger" />
    </link>
    <link name="${prefix}rightfinger">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}" />
        <geometry>
          <mesh filename="package://franka_description/meshes/collision/finger.stl" />
        </geometry>
      </collision>
      <xacro:inertial name="rightfinger" />
   </link>
    <joint name="${prefix}finger_joint1" type="prismatic">
      <parent link="${prefix}hand"/>
      <child link="${prefix}leftfinger"/>
      <origin xyz="0 0 0.0584" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="20" lower="0.0" upper="0.04" velocity="0.2"/>
    </joint>
    <joint name="${prefix}finger_joint2" type="prismatic">
      <parent link="${prefix}hand"/>
      <child link="${prefix}rightfinger"/>
      <origin xyz="0 0 0.0584" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <limit effort="20" lower="0.0" upper="0.04" velocity="0.2"/>
      <mimic joint="${prefix}finger_joint1" />
    </joint>
  </xacro:macro>
</robot>
