FROM osrf/ros:noetic-desktop-focal
RUN apt-get update -y && apt-get install -y \
    clang-6.0 \
    clang-format-6.0 \
    clang-tidy-6.0 \
    liborocos-kdl-dev \
    python3-catkin-tools \
    ros-noetic-libfranka \
    ros-noetic-ros-control \
    ros-noetic-eigen-conversions \
    ros-noetic-gazebo-dev \
    ros-noetic-gazebo-ros-control \
    && rm -rf /var/lib/apt/lists/*
