FROM osrf/ros:kinetic-desktop-xenial
RUN apt-get update -y && apt-get install -y --allow-unauthenticated \
    clang-6.0 \
    clang-format-6.0 \
    clang-tidy-6.0 \
    python3-pip \
    ros-kinetic-libfranka \
    ros-kinetic-ros-control \
    ros-kinetic-eigen-conversions \
    ros-kinetic-gazebo-dev \
    ros-kinetic-gazebo-ros-control \
    ros-kinetic-orocos-kdl \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install -U catkin_tools
